{{- include "wa.init" (list . "waconsole") }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: dwc-network-policy
  labels:
{{ include "wa.console.labels" . | indent 5 }}
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels:
{{ include "wa.console.labels" . | indent 7 }}
  ingress:
  - ports:
      - protocol: TCP
        port: 9443
      - protocol: TCP
        port: 9444