{{- if .Values.global.extraImageName }}
{{ $fullName := include "fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-extra
  labels:
    app: {{ $fullName }}-extra
{{ include "uno.common.label" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $fullName }}-extra
    app.kubernetes.io/instance: {{ $fullName }}-extra
{{- end }}