{{ $fullName := include "fullname" . }}
{{ $saName := include "uno.serviceAccount" . }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $saName }}
  labels:
{{ include "uno.common.label" . | indent 4 }}
imagePullSecrets:
  - name: sa-uno
  - name: sa-{{ .Release.Namespace }}
{{- if .Values.global.hclImagePullSecret }}
  - name: {{ .Values.global.hclImagePullSecret }}
{{- end }}


